

# -- build stage ---------------------------------------------
FROM golang:alpine AS build-env

ADD . /src

# Command works:

# VERSION to use with 'FROM alpine' below:
#RUN cd /src && go build -o demo-binary

# VERSION to use with 'FROM scratch' below:
RUN cd /src && __STAGE1_BUILD__

RUN ls -al  /src/demo-binary; ls -alh /src/demo-binary; /src/demo-binary -v -die; exit 0

# -- final stage ---------------------------------------------

FROM __FROM_IMAGE__ AS runtime-image

ADD static    /app/static
ADD templates /app/templates

WORKDIR /app
COPY    --from=build-env /src/demo-binary /app/

RUN ls -al demo-binary
RUN ls -alh demo-binary

EXPOSE __EXPOSE_PORT__
ENTRYPOINT ["/app/demo-binary"]

CMD __TEMPLATE_CMD__

